services:
  plot:
    build:
      context: ./plot
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:admin@mongo:27017/train_db

  checker:
    build: ./checker
    depends_on:
      - mongo
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://admin:admin@mongo:27017/train_db
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin

volumes:
  mongo_data:
